moderation_notes.moderation_note_severity.*:
  type: config_entity
  label: 'Moderation note severity'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    severity_level:
      type: string
      label: 'Severity level'
    blocked_moderation_transitions:
      type: sequence
      sequence:
        type: string
        label: 'Blocked moderation transitions'
